Repository LunarTides/Hearthstone.js, pull requests merged in 2023-04, with the labels that each got.

#25 Fixed Master's Call
  cards/Classes/Hunter/Spells/3 Cost/masters_call.js
  src/functions.js
  src/interact.js
Labels: enhancement, priority: high, time: short, card

#27 Made `this has all minion types` work
  cards/Classes/Hunter/Spells/3 Cost/masters_call.js
  cards/Classes/Neutral/Minions/1 Cost/toxfin.js
  cards/Classes/Neutral/Minions/3 Cost/nerubian_vizier.js
  cards/Classes/Neutral/Minions/8 Cost/invincible.js
  cards/Classes/Neutral/Minions/9 Cost/dragonqueen_alexstrasza.js
  cards/Classes/Neutral/Minions/9 Cost/flesh_behemoth.js
  cards/Classes/Neutral/Minions/9 Cost/nzoth_god_of_the_deep.js
  cards/Classes/Paladin/Minions/2 Cost/redscale_dragontamer.js
  cards/Classes/Paladin/Minions/4 Cost/goldwing.js
  cards/Classes/Paladin/Minions/5 Cost/the_purator.js
  cards/Classes/Paladin/Minions/8 Cost/murgur_murgurgle_prime.js
  cards/Classes/Shaman/Minions/2 Cost/firemancer_flurgl.js
  cards/Classes/Shaman/Quests/Command The Elements/stormcaller_brukan.js
  cards/Classes/Shaman/Spells/2 Cost/ice_fishing.js
  src/functions.js
Labels: bug, priority: medium, time: short

#32 Added enchantments
  cards/Classes/Druid/Spells/2 Cost/lunar_eclipse.js
  cards/Classes/Druid/Spells/8 Cost/celestial_alignment.js
  cards/Classes/Hunter/Secrets/freezing_trap.js
  cards/Classes/Hunter/Secrets/zombees.js
  cards/Classes/Hunter/Spells/2 Cost/dun_baldar_bunker.js
  cards/Classes/Mage/Minions/2 Cost/prismatic_elemental.js
  cards/Classes/Neutral/Minions/10 Cost/thaddius_monstrosity.js
  cards/Classes/Neutral/Minions/3 Cost/generous_mummy.js
  cards/Classes/Neutral/Minions/3 Cost/nerubian_vizier.js
  cards/Classes/Neutral/Minions/4 Cost/vanndar_stormpike.js
  cards/Classes/Neutral/Minions/5 Cost/loatheb.js
  cards/Classes/Neutral/Minions/6 Cost/emperor_thaurissan.js
  cards/Classes/Neutral/Minions/9 Cost/dragonqueen_alexstrasza.js
  cards/Classes/Neutral/Spells/9 Cost/the_sunwell.js
  cards/Classes/Paladin/Minions/3 Cost/stonehearth_vindicator.js
  cards/Classes/Paladin/Minions/9 Cost/lightray.js
  cards/Classes/Paladin/Spells/2 Cost/legendary_invitation.js
  cards/Classes/Priest/Minions/2 Cost/radiant_elemental.js
  cards/Classes/Priest/Minions/3 Cost/nazmani_bloodweaver.js
  cards/Classes/Priest/Spells/2 Cost/insight_corrupted.js
  cards/Classes/Priest/Spells/3 Cost/palm_reading.js
  cards/Classes/Priest/Spells/8 Cost/power_word_fortitude.js
  cards/Classes/Rogue/Spells/0 Cost/preparation.js
  cards/Classes/Rogue/Spells/4 Cost/academic_espionage.js
  cards/Classes/Shaman/Minions/6 Cost/grumble_worldshaker.js
  cards/Classes/Warlock/Minions/3 Cost/tamsin_roame.js
  cards/Classes/Warrior/Spells/10 Cost/shield_shatter.js
  cards/Tests/enchantments.js
  src/card.js
  src/game.js
Labels: enhancement, priority: medium, time: long

#35 Allowed user to switch between ai attack models
  config/ai.json
  src/ai.js
  src/interact.js
Labels: enhancement, priority: low, time: short

#37 Improved backups
  cards/Classes/Druid/Minions/4 Cost/floop.js
  cards/Classes/Warrior/Minions/9 Cost/rattlegore.js
  src/card.js
  src/interact.js
Labels: enhancement, priority: low, time: short

#53 Made the card creator more readable
  card_creator/index.js
  index.js
Labels: time: short, card creator

#57 Fixed a bug in the deck creator.
  deck_creator/index.js
Labels: bug, priority: high, time: short, deck creator
